### ISSUE TITLE
Change mode dynamically to CodeMirror Editor in AngularJS

### ISSUE THREAD

**Issue by mohitsuman** [angular-ui/ui-codemirror#13]
I am using AngularJS , I need to change the mode of Code-Mirror Dynamically as soon as the language name changes.

example: mode:{{ language}} , I want the name of language to be stated as the new mode for codemirror.

**Comment by pioneer903** [comment]
Hey @douglasduteil, seems like the demo you provided is not working at all.
The demo that is on the main page in pnkr doesn't work either http://embed.plnkr.co/i3NJ3oavmGCwBrBaMBTX/preview
Any suggestions?

Thanks
