### ISSUE TITLE
Error calling scope.$applyAsync

### ISSUE THREAD

**Issue by amarandon** [angular-ui/ui-codemirror#89]
This error is visible on the Mode-Changing demo at http://angular-ui.github.io/ui-codemirror/
Enter text in the editor and you'll see the error message in the console.
On Firefox: `TypeError: scope.$applyAsync is not a function`
On Chrome: `Uncaught TypeError: Object #<h> has no method '$applyAsync'`

Error is triggered at line 130 of ui-codemirror.js

**Comment by amarandon** [comment]
Thank you!

**Comment by douglasduteil** [comment]
Thank you for spotting it :+1:
