### ISSUE TITLE
Upgrade Codemirror dependency to 4.12

### ISSUE THREAD

**Issue by quietlyconfident** [angular-ui/ui-codemirror#92]
Codemirror is currently released at 4.12.  ui-codemirror is currently pinned to `~4.8`.

Could the bower.json file be updated to use the more recent codemirror?

**Comment by SyntaxRules** [comment]
:+1: 4.13.0 is out and if you're really adventurous 5.0.0 is out too.

**Comment by episodeyang** [comment]
Yeah, can we bump the version to 5.0.x?

**Comment by episodeyang** [comment]
It has been couple of month now. I can submit a PR. @douglasduteil Would it be possible to have it merged soon?

**Comment by benjiwheeler** [comment]
I would love to see the version advanced as well! I'm in favor of >=5.0.0 <=5.2 :)

**Comment by douglasduteil** [comment]
Alright in progress !
sry for the wait...
