### ISSUE TITLE
Theme/mode not changing

### ISSUE THREAD

**Issue by carlossdparaujo** [angular-ui/ui-codemirror#96]
This is my code:

HTML:
<div ui-codemirror="editorOptions"></div>

JS:
.controller('EditorController', ['$scope', function($scope) {
  	$scope.editorOptions = {
        lineWrapping: true,
        mode: "javascript",
        theme: "monokai",
        lineNumbers: true
    };
}]);

But the theme and mode never changes, actually only lineNumbers is working I think

**Comment by douglasduteil** [comment]
Do you have a running demo ?

**Comment by carlossdparaujo** [comment]
Oh sorry, I actually found the problem in my code and solved it, I forgot to close the issue, closing it now! Sorry again!

**Comment by Chris2011** [comment]
What was the solution?

**Comment by carlossdparaujo** [comment]
If i'm not mistaken, I was missing a configuration file so the theme would work, but I don't quite remember sorry :/

**Comment by Chris2011** [comment]
Nevermind, I copied the directive code and fixed that by my own. I think it was that I missed the mode js files to include.

**Comment by ghost** [comment]
@Chris2011  modeJs link please.

**Comment by Chris2011** [comment]
@jijo4u  excuse me?
