### ISSUE TITLE
Required mode file is not mentioned in the documentation

### ISSUE THREAD

**Issue by bramcordie** [angular-ui/ui-codemirror#99]
I just set up ui-codemirror in a project and had some trouble getting it to show highlighting. After setting the right mode (I'm highlighting solr) in editor options, colors were still missing, eg: 

```
editorOptions = {
  mode: 'solr',
};
```

I went to the codemirror documentation and it mentions you have to include a special file for each mode.
When [using wiredep](https://github.com/taptapship/wiredep#bower-overrides) for example, the following override in your bower.json file will do the trick:

```
"codemirror": {
  "main": [
    "lib/codemirror.js",
    "lib/codemirror.css",
    "mode/solr/solr.js"
  ]
}
```

You can also include the required .js file manually...

Are there any mode files included by default or why is this not mentioned in the documentation?

**Comment by douglasduteil** [comment]
> Are there any mode files included by default 

No. UI.CodeMirror or CodeMirror don't have default mode files. You have to provide the mode you want/need manually.

> why is this not mentioned in the documentation?

UI.CodeMirror only provide a interface to use CodeMirror in the Angular word.
You will need the CodeMirror documentation to use UI.CodeMirror.
